#pragma once
#include "Arduino.h"

const int ENTRADA_BOTAO_LIGAR = 2;
const int ENTRADA_BOTAO_TROCA_CORES = 4;
const int ENTRADA_BOTAO_DIMINUIR_LUZ = 7;
const int ENTRADA_BOTAO_AUMENTAR_LUZ = 8;

const int SAIDA_LUZ_BRANCA = 10;
const int SAIDA_LUZ_AMARELA = 11;

const int INTENSIDADE_INICIAL_LUZ_PORCENTAGEM = 50;
const int INTENSIDADE_MINIMA_LUZ_PORCENTAGEM = 0;
const int INTENSIDADE_MAXIMA_LUZ_PORCENTAGEM = 100;

const int TEMPO_DETECTAR_BOTAO_LIGAR_MS = 1000; 
const int TEMPO_DETECTAR_OUTROS_BOTOES_MS = 500; 
